name: linting, testing, building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build production project
        run: npm run build:prod
        if: always()

      - name: Linting typescript
        run: npm run lint:ts
        if: always()

      - name: Linting scss
        run: npm run lint:scss
        if: always()

      - name: Unit testing
        run: npm run test:unit
        if: always()
